export const data = {
    thongTinPhim: {
      maLichChieu: 16105,
      tenCumRap: 'BHD Star Cineplex - Bitexco',
      tenRap: 'Rạp 7',
      diaChi: 'L3-Bitexco Icon 68, 2 Hải Triều, Q.1',
      tenPhim: 'Black Windo',
      hinhAnh: 'http://movie0706.cybersoft.edu.vn/hinhanh/black-windo_gp01.jpg',
      ngayChieu: '02/01/2019',
      gioChieu: '10:01',
    },
    danhSachGhe: [
      {
        maGhe: 49961,
        tenGhe: '01',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '01',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49962,
        tenGhe: '02',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '02',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49963,
        tenGhe: '03',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '03',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49964,
        tenGhe: '04',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '04',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49965,
        tenGhe: '05',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '05',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'adminanhkhoa',
      },
      {
        maGhe: 49966,
        tenGhe: '06',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '06',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'adminanhkhoa',
      },
      {
        maGhe: 49967,
        tenGhe: '07',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '07',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'adminanhkhoa',
      },
      {
        maGhe: 49968,
        tenGhe: '08',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '08',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'adminanhkhoa',
      },
      {
        maGhe: 49969,
        tenGhe: '09',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '09',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'adminanhkhoa',
      },
      {
        maGhe: 49970,
        tenGhe: '10',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '10',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49971,
        tenGhe: '11',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '11',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49972,
        tenGhe: '12',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '12',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49973,
        tenGhe: '13',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '13',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49974,
        tenGhe: '14',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '14',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'alinguyen197',
      },
      {
        maGhe: 49975,
        tenGhe: '15',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '15',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 49976,
        tenGhe: '16',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '16',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49977,
        tenGhe: '17',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '17',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49978,
        tenGhe: '18',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '18',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49979,
        tenGhe: '19',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '19',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49980,
        tenGhe: '20',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '20',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49981,
        tenGhe: '21',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '21',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49982,
        tenGhe: '22',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '22',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49983,
        tenGhe: '23',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '23',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49984,
        tenGhe: '24',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '24',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49985,
        tenGhe: '25',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '25',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'thanhthuat',
      },
      {
        maGhe: 49986,
        tenGhe: '26',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '26',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 49987,
        tenGhe: '27',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '27',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 49988,
        tenGhe: '28',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '28',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49989,
        tenGhe: '29',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '29',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49990,
        tenGhe: '30',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '30',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49991,
        tenGhe: '31',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '31',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 49992,
        tenGhe: '32',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '32',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49993,
        tenGhe: '33',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '33',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49994,
        tenGhe: '34',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '34',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49995,
        tenGhe: '35',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '35',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49996,
        tenGhe: '36',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '36',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49997,
        tenGhe: '37',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '37',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49998,
        tenGhe: '38',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '38',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 49999,
        tenGhe: '39',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '39',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50000,
        tenGhe: '40',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '40',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50001,
        tenGhe: '41',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '41',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50002,
        tenGhe: '42',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '42',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50003,
        tenGhe: '43',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '43',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50004,
        tenGhe: '44',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '44',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50005,
        tenGhe: '45',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '45',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50006,
        tenGhe: '46',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '46',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: '1234z',
      },
      {
        maGhe: 50007,
        tenGhe: '47',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '47',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50008,
        tenGhe: '48',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '48',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50009,
        tenGhe: '49',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '49',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50010,
        tenGhe: '50',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '50',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50011,
        tenGhe: '51',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '51',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50012,
        tenGhe: '52',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '52',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50013,
        tenGhe: '53',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '53',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50014,
        tenGhe: '54',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '54',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50015,
        tenGhe: '55',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '55',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50016,
        tenGhe: '56',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '56',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50017,
        tenGhe: '57',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '57',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50018,
        tenGhe: '58',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '58',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 50019,
        tenGhe: '59',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '59',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 50020,
        tenGhe: '60',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '60',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50021,
        tenGhe: '61',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '61',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50022,
        tenGhe: '62',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '62',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50023,
        tenGhe: '63',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '63',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 50024,
        tenGhe: '64',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '64',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50025,
        tenGhe: '65',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '65',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50026,
        tenGhe: '66',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '66',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50027,
        tenGhe: '67',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '67',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50028,
        tenGhe: '68',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '68',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'abc1234',
      },
      {
        maGhe: 50029,
        tenGhe: '69',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '69',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50030,
        tenGhe: '70',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '70',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50031,
        tenGhe: '71',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '71',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50032,
        tenGhe: '72',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '72',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50033,
        tenGhe: '73',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '73',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50034,
        tenGhe: '74',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '74',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50035,
        tenGhe: '75',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '75',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50036,
        tenGhe: '76',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '76',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50037,
        tenGhe: '77',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '77',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50038,
        tenGhe: '78',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '78',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: '123@admin',
      },
      {
        maGhe: 50039,
        tenGhe: '79',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '79',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50040,
        tenGhe: '80',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '80',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 50041,
        tenGhe: '81',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '81',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50042,
        tenGhe: '82',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '82',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50043,
        tenGhe: '83',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '83',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50044,
        tenGhe: '84',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '84',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50045,
        tenGhe: '85',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '85',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50046,
        tenGhe: '86',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '86',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50047,
        tenGhe: '87',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '87',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50048,
        tenGhe: '88',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '88',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50049,
        tenGhe: '89',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '89',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50050,
        tenGhe: '90',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '90',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'alinguyen197',
      },
      {
        maGhe: 50051,
        tenGhe: '91',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '91',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'alinguyen197',
      },
      {
        maGhe: 50052,
        tenGhe: '92',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '92',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50053,
        tenGhe: '93',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '93',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50054,
        tenGhe: '94',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '94',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50055,
        tenGhe: '95',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '95',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 50056,
        tenGhe: '96',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '96',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'gia1999',
      },
      {
        maGhe: 50057,
        tenGhe: '97',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '97',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50058,
        tenGhe: '98',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '98',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50059,
        tenGhe: '99',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '99',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50060,
        tenGhe: '100',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '100',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50061,
        tenGhe: '101',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '101',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50062,
        tenGhe: '102',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '102',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50063,
        tenGhe: '103',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '103',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50064,
        tenGhe: '104',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '104',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50065,
        tenGhe: '105',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '105',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50066,
        tenGhe: '106',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '106',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'chithanh_admin',
      },
      {
        maGhe: 50067,
        tenGhe: '107',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '107',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'chithanh_admin',
      },
      {
        maGhe: 50068,
        tenGhe: '108',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '108',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50069,
        tenGhe: '109',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '109',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50070,
        tenGhe: '110',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '110',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'alinguyen197',
      },
      {
        maGhe: 50071,
        tenGhe: '111',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '111',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50072,
        tenGhe: '112',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '112',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50073,
        tenGhe: '113',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '113',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50074,
        tenGhe: '114',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '114',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50075,
        tenGhe: '115',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '115',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50076,
        tenGhe: '116',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '116',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50077,
        tenGhe: '117',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '117',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50078,
        tenGhe: '118',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '118',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50079,
        tenGhe: '119',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '119',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50080,
        tenGhe: '120',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '120',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50081,
        tenGhe: '121',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '121',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50082,
        tenGhe: '122',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '122',
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 50083,
        tenGhe: '123',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '123',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50084,
        tenGhe: '124',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '124',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50085,
        tenGhe: '125',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '125',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50086,
        tenGhe: '126',
        maRap: 467,
        loaiGhe: 'Vip',
        stt: '126',
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50087,
        tenGhe: '127',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '127',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 50088,
        tenGhe: '128',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '128',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50089,
        tenGhe: '129',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '129',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50090,
        tenGhe: '130',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '130',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50091,
        tenGhe: '131',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '131',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50092,
        tenGhe: '132',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '132',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50093,
        tenGhe: '133',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '133',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50094,
        tenGhe: '134',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '134',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50095,
        tenGhe: '135',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '135',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50096,
        tenGhe: '136',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '136',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50097,
        tenGhe: '137',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '137',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50098,
        tenGhe: '138',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '138',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'chucuoi2',
      },
      {
        maGhe: 50099,
        tenGhe: '139',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '139',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50100,
        tenGhe: '140',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '140',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50101,
        tenGhe: '141',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '141',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50102,
        tenGhe: '142',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '142',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50103,
        tenGhe: '143',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '143',
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: 'stringsdf',
      },
      {
        maGhe: 50104,
        tenGhe: '144',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '144',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50105,
        tenGhe: '145',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '145',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50106,
        tenGhe: '146',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '146',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50107,
        tenGhe: '147',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '147',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50108,
        tenGhe: '148',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '148',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50109,
        tenGhe: '149',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '149',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50110,
        tenGhe: '150',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '150',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50111,
        tenGhe: '151',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '151',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50112,
        tenGhe: '152',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '152',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50113,
        tenGhe: '153',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '153',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50114,
        tenGhe: '154',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '154',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50115,
        tenGhe: '155',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '155',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50116,
        tenGhe: '156',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '156',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50117,
        tenGhe: '157',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '157',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50118,
        tenGhe: '158',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '158',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50119,
        tenGhe: '159',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '159',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50120,
        tenGhe: '160',
        maRap: 467,
        loaiGhe: 'Thuong',
        stt: '160',
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
    ],
  };
  